name: Master build

on:
  push:
    branches:
      - main
    tags:
      - '*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  GITHUB_DUMP: ${{ toJson(github) }}


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Dump env
        shell: bash
        run: |
          echo "github env:"
          echo "$GITHUB_DUMP"

      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{ github.event.push.ref }}

      - name: Setup Python toolchain
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Python dependencies
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Build Pyrun
        shell: bash
        run: |
            python make.py ${{ matrix.python-version }}
